version: '3.9'

services:
  wshopping:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - .:/home/node/wshopping
    command: >
      bash -c 'npm cache clean --force &&
               npm install --legacy-peer-deps &&
               npm start -- --host 0.0.0.0 --disable-host-check'
