version: '3.9'

services:
  wshopping-test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9876:9876
    volumes:
      - .:/home/node/wshopping
    command: >
      bash -c 'npm cache clean --force &&
               npm install --legacy-peer-deps &&
               npm test -- --code-coverage --watch=false'
